### ISSUE TITLE
[PROPOSAL] add formatting method (nest, interfacing with pretty-printing)

### ISSUE THREAD

**Issue by doudou** [TwP/logging#119]
I have widely used a few extensions to Ruby's code Logger class to build hierarchical loggers, and also to help formatting log messages, close to what pretty-printing does. See for instance https://github.com/orocos-toolchain/utilrb/tree/master/lib/utilrb/logger/nest.rb and other files in https://github.com/orocos-toolchain/utilrb/tree/master/lib/utilrb/logger/

I'd like to get rid of this 'utilrb' thing ... So I was looking for alternatives. Logging is obviously a lot better when it comes to hierarchies and configurability, so I'd love to migrate to it. However, I was wondering if there would be an interest from you that I port the formatting stuff to Logging.

**Comment by doudou** [comment]
Ping ... note that *I* would do the work, just want to know if the functionality would be well-received or not

**Comment by TwP** [comment]
I'm not sure what formatting part you are looking for. The logging gem already has the concept of [`layouts`](https://github.com/TwP/logging/tree/master/lib/logging/layouts) which format messages in various ways. The [`Pattern`](https://github.com/TwP/logging/blob/master/lib/logging/layouts/pattern.rb) is by far the most flexible.

So I'm not exactly sure what you are proposing.

**Comment by doudou** [comment]
The original description is indeed very much lacking in explanations ... sorry.

One thing I was missing is the ability to indent log messages generated by methods called, for instance:

```
logger.debug "a debug message"
logger.nest(4) do
   call_a_method # messages generated by this method are indented
end
```

another formatting-related method is `log_pp`, which pretty-prints an object on the logger, but formatting each line of the pretty-printed output separately.

**Comment by TwP** [comment]
> # messages generated by this method are indented

In the logging framework, the generation of log events and the formatting of those events are two separate concerns. The `logger` objects are only concerned with generating events. The formatting of events is handled by various [`layouts`](https://github.com/TwP/logging/tree/master/lib/logging/layouts):

* [Basic layout](https://github.com/TwP/logging/blob/master/lib/logging/layouts/basic.rb)
* [Pattern layout](https://github.com/TwP/logging/blob/master/lib/logging/layouts/pattern.rb)
* [JSON layout](https://github.com/TwP/logging/blob/master/lib/logging/layouts/parseable.rb#L13-L15) - emits log events in JSON format
* [YAML layout](https://github.com/TwP/logging/blob/master/lib/logging/layouts/parseable.rb#L19-L21) - emits log events in YAML format

Regarding a pretty printing logger, that would also be handled by the layout.

**Comment by doudou** [comment]
Didn't know about the layout thing ... Thanks for the info.

However, would it make sense to allow the logger caller to specify a "hierarchy" of sorts ? As a hint to the layout objects.

In my example, method X calls method Y, and the caller wants the events to be logged hierarchically when the layout supports it. 
~~~
logger.debug "a debug message"
logger.nest do
   call_a_method # messages generated by this method on 'logger' are logged at another hierarchy level
end
~~~

**Comment by TwP** [comment]
> the caller wants the events to be logged hierarchically

I'm not sure what you mean by this. The Logging framework already organizes `Logger` instances in a hierarchy. Take a look at the [examples/hierarchies.rb](https://github.com/TwP/logging/blob/master/examples/hierarchies.rb) file. Is this what you are referring to?

**Comment by doudou** [comment]
> I'm not sure what you mean by this.

My understand is that the logger hierarchy is mostly used to split configuration (i.e. set various levels) and identify the origin (per-subsystem) of the logging events.

What I am trying to achieve with this hierarchy is to (optionally) represent the relationship between the logging events and the execution flow. By nesting the logging events hierarchically, one can infer the reason *why* some events have been generated. It gives context to logging events generated by helper methods that are called from different parts of the system.

A typical output looks like

```
INFO: resolving merge among 10 tasks
INFO:   resolving Task(id: 20):
INFO:     <output match 0> 
INFO:     <output match 0>
INFO:     <output match 0>
INFO:   resolved Task(id: 10): 0 matches
```

The "resolving merge" level, the "resolving task" and the "output match" levels are generated at different places in the code, only the logger outputs them in a hierarchical way to improve understanding. This is important as e.g. the matching method (which logs the matches) is used elsewhere, where the level of hierarchy is different, so it's just not possible (and, in general, IMO not desirable) to hardcode a level of indentation.

**Comment by TwP** [comment]
I think what you are looking for is the [`NestedDiagnosticContext`](https://github.com/TwP/logging/blob/master/lib/logging/diagnostic_context.rb#L267). See if this little trick works for you.

```ruby
Logging.ndc << nil    # need at least one item in the context array

logger.debug "message 1"   # no nesting

Logging.ndc.push(nil) do   # add another item to the context array so that `context.join(" ")` returns one space - i.e. joining the two `nil` values

  logger.debug "message 2"  # one level of nesting since we are join two `nil` values with a space

  Logging.ndc.push(nil) do  # add another level of nesting
    logging.debug "message 3"
  end
end
```

To make this work, we'll need to configure a [`Pattern`](https://github.com/TwP/logging/blob/master/lib/logging/layouts/pattern.rb) layout to output the nested diagnostic context.

```ruby
layout = Logging.layouts.pattern(:pattern => '%5l: %x%m\n')
```

The `%x` in the pattern there instructs the layout to insert the contents of the nested diagnostic context joined by a single space character. You can change that to multiple space characters thusly:

```ruby
layout = Logging.layouts.pattern(:pattern => '%5l: %x{  }%m\n')
```

You can put whatever characters you want in between the curly braces and they will be used when joining context items. Please take a look at the [pattern layout options](https://github.com/TwP/logging/blob/master/lib/logging/layouts/pattern.rb#L11-L149) in the documentation - there are quite a few things you can do.

Give this approach a shot. I would also recommend doing some benchmarking to see how badly these `push` operations affect performance.

Because implementing this type of feature relies on two disjoint pieces of code - the nested diagnostic context, and the pattern layout - I do not foresee it being a viable feature in the Logging framework. To implement the `nest` function ins the fashion would prevent the user from using the nested diagnostic context for other purposes. And it would force the user to implement a very specific pattern layout.

The code I've written here is an interesting hack at best. You can hide some of the ugliness by implementing your own `nest` method that performs the `Logging.ndc.push(nil)` trick, and then use that `nest` method throughout your own code.

**Comment by TwP** [comment]
Here is a quick and dirty example:

```ruby
require 'logging'

module Logging
  def self.nest
    Logging.ndc.push(nil) do
      yield
    end
  end
end

Logging.ndc << nil


layout = Logging.layouts.pattern(:pattern => '%5l: %x{  }%m\n')
Logging.appenders.stdout(:layout => layout)

logger = Logging.logger.root
logger.add_appenders("stdout")
logger.level = :debug

logger.debug "message 1"

Logging.nest do
  logger.info "message 2"
  Logging.nest do
    logger.warn "message 3"
  end
  logger.debug "this is working"
end
```
