### ISSUE TITLE
Rolling file appender with gzip compression

### ISSUE THREAD

**Issue by alextk** [TwP/logging#141]
Compressing rolled files with gzip would give around tenfold decrease in file size, so for example having 30 days of logs in prod, each log file ~500mb in average, would reduce them from ~15gb in total to only 1.5gb.

I think that adding `:gzip` option to existing rolling file appender would be best:

```
Logging.appenders.rolling_file( 'gzipped_rolling_file',
    :filename => File.join(Rails.root, '/log/', "production.log"),
    :keep => 31,
    :age => 'daily',
    :truncate => false,
    :auto_flushing => true,
    :gzip => true
  )
```

**Comment by TwP** [comment]
I'm hesitant to build this into Logging itself. The reason being that all activities performed by the Logging framework happen in-process. While Logging is busy gzipping a file, your application will not be doing work. It will be sitting there waiting for Logging to finish the compression.

Rolling of log files is built-in to the logging framework so that you don't have to write a SIGHUP handler in order to play nicely with `logrotate` and other similar tools.

I'm open to being persuaded otherwise, but I don't see this feature as being in scope for the Logging framework.
