### ISSUE TITLE
raise an exception for fatal or any other level?

### ISSUE THREAD

**Issue by NicoLugil** [TwP/logging#228]
As far as I can see none of the levels actually raise an exception? I actually had assumed that for example fatal would.
For my application I want fatal and sometimes error to raise an exception.

E.g. I would like to be able to write something like:

```
require 'logging'

logger = Logging.logger(STDOUT)
logger.level = :warn
logger.raise_on :error, :fatal     # imaginary syntax
begin
   logger.debug "this debug message will not be output by the logger"
   logger.warn "this is your last warning"
   logger.fatal "ohoh"
rescue LoggingException => e
  puts e
end
```

Maybe I am overlooking something, and this is already possible? Or is it the idea to do this via an appender?

**Comment by TwP** [comment]
Raising exceptions is outside the purview of the Logging framework. The purpose of the Logging gem is to send messages to logging destinations. If you also want to raise an exception, then you will need to explicitly write the `raise` code yourself directly after the call to `logger.fatal`.

The `logger.fatal` method stores a record of what happened for later debugging.

The `raise` method is the responsibility of your code since only you know the best recovery path for the fatal condition that occurred.
