### ISSUE TITLE
Remove YAML configurator

### ISSUE THREAD

**Issue by TwP** [TwP/logging#43]
YAML configuration is no longer supported in the Logging framework. The DSL style configuration is the way forward.

**Comment by jstultz** [comment]
Hi, I realize this is totally ancient, but I came across this because a coworker encountered a need to update from 1.8.2 in a component we haven't really modified in quite a while. We were relying on the YAML configurator; could you perhaps point me somewhere that clears up what the DSL style configuration you're referring to here is?

**Comment by TwP** [comment]
Take a look at the [`examples`](https://github.com/TwP/logging/tree/master/examples) folder here in the repository. Specifically the [`examples/appenders.rb`](https://github.com/TwP/logging/blob/master/examples/appenders.rb) file and the [`examples/layouts.rb`](https://github.com/TwP/logging/blob/master/examples/layouts.rb) file provide examples of how to configure layouts and appenders using the DSL style.

DSL might be a little misleading ... the examples above :point_up: are using the methods defined in the library. There is not a real DSL class. So your confusion and request for clarification here are completely understandable.
