### ISSUE TITLE
Need an easier way to get Logger._dump_configuration as a string.

### ISSUE THREAD

**Issue by keithrbennett** [TwP/logging#65]
The output of Logger._dump_configuration is unlikely to be huge.  I suggest refactoring it so that there is a method that returns a string, and then _dump_configuration() becomes a thin wrapper around that.  Reason: I want to get a string representation of the log configuration for insertion into another string. It feels upside down and overly complicated to have to create a StringIO and then extract a string from it.

**Comment by TwP** [comment]
Creating a `StringIO` instance and then calling `string` at the end is exactly how I would solve this problem in the library. 

Because each logger instance is going to write it's own configuration information, we need some object that collects this data. We could pass around an Array. Each logger appends its configuration to the Array, and at the end of the process the Array gets written to an IO instance.

That might be an elegant solution. If you pass an IO object to the method, then the configuration is dumped to the IO. If you pass an Array, then the configuration is dumped to the Array. Yeah, that is definitely the way to go here.
