### ISSUE TITLE
class loggers should inherit appenders from the root logger

### ISSUE THREAD

**Issue by mdundas** [TwP/logging#92]
Happy to see this log4j implementation for Ruby.

It looks like the class loggers are not inheriting the appenders i assign to the root logger.
Is this by design or am i missing something?  In log4j, you can assign an appender to a root logger and the class loggers will pick them up.  I suppose i could assign the appenders in every class but thats a bit tedious.

thx
-matt

**Comment by TwP** [comment]
Instead of passing appenders to children each logger will pass log events up the hierarchy, and then each logger will send that event to its appenders. See the [`log_event`](https://github.com/TwP/logging/blob/master/lib/logging/logger.rb#L392-L402) method for the details.

You can set the additivity of a logger so it will not pass events up the logger hierarchy. You would do this for logging sensitive data (credentials, credit card numbers, etc) to a separate appender then regular log messages.
